# Simple Math in R 

In [1]:
3-2

[1] 1

In [2]:
4>3

[1] TRUE

In [3]:
4 == 4

[1] TRUE

In [4]:
(4==4)&&(3>2)

[1] TRUE

In [5]:
!(3==4)

[1] TRUE

# variable assignment

In [6]:
a <- 3+3

In [7]:
print(a)

[1] 6


In [8]:
a= 3+3

In [9]:
print(a)

[1] 6


In [10]:
greetings <- "hey, buddy!"

In [11]:
print(greetings)

[1] "hey, buddy!"


In [13]:
some_logic <-TRUE

### The Vector

In [14]:
dat <- c(4,5,6,23,2)

In [15]:
print(dat)

[1]  4  5  6 23  2


In [17]:
v1 <- c(1,2,3)
v2 <- c(5,4,3)
v <- c(v1,v2)

In [18]:
my_vec <-rep(0,10)

In [19]:
print(my_vec)

 [1] 0 0 0 0 0 0 0 0 0 0


In [20]:
m <- 1:20

In [22]:
v3 <- seq(-10,10, 2)

In [23]:
v3

[1] -10  -8  -6  -4  -2   0   2   4   6   8  10

In [24]:
print(v3)

 [1] -10  -8  -6  -4  -2   0   2   4   6   8  10


In [25]:
print(seq(-10,10,2))

 [1] -10  -8  -6  -4  -2   0   2   4   6   8  10


In [26]:
u <- seq(-2,2,1)

In [27]:
print(u)

[1] -2 -1  0  1  2


In [28]:
u <- -2:2

In [29]:
print(u)

[1] -2 -1  0  1  2


### Indexing and Slicing

In [30]:
v <- rnorm(5)

In [31]:
v

[1] -1.60401660  0.07079597 -0.57798222  0.17401981  1.59512438

In [32]:
v[2]

[1] 0.07079597

In [33]:
v[1:3]

[1] -1.60401660  0.07079597 -0.57798222

In [34]:
v[c(1,3)]

[1] -1.6040166 -0.5779822

In [35]:
print(v)

[1] -1.60401660  0.07079597 -0.57798222  0.17401981  1.59512438


In [36]:
v[-3]

[1] -1.60401660  0.07079597  0.17401981  1.59512438

### assignment with indexing

In [37]:
u <-c(5,6,8,22)

In [38]:
u[1] <- 0

In [39]:
print(u)

[1]  0  6  8 22


In [40]:
u3 <- u[1:3]

In [41]:
print(u3)

[1] 0 6 8


In [43]:
i <- c(5,2,8,8,9,9)

In [44]:
i[c(2,4,6)]

[1] 2 8 9

In [45]:
v <- c(10,20,30)

In [47]:
v[1:2] <- 0

In [48]:
print(v)

[1]  0  0 30


In [49]:
v1 <- c(10,20,30,40,50)

In [50]:
v2 <- v1[c(1,3,5)]

In [51]:
print(v2)

[1] 10 30 50


In [52]:
v1 <- c(10,20,30,40,50)
idx <- c(1,3,5)
v2 <- v1[idx]
print(v2)

[1] 10 30 50


In [53]:
v1 <- seq(10,50,10)   #this is creating a vector
idx <- c(TRUE, FALSE, TRUE, FALSE, TRUE)
v2 <-v1[idx]
print(v2)

[1] 10 30 50


# Vectorization of Operations

In [54]:
v <- c(44,55,66)
v-20

[1] 24 35 46

In [55]:
v*2

[1]  88 110 132

In [56]:
v/5

[1]  8.8 11.0 13.2

In [57]:
v>50

[1] FALSE  TRUE  TRUE

## Useful Operations on Vectors

In [58]:
v <- rnorm(10)

In [59]:
n <-length(v)

In [60]:
print(n)

[1] 10


In [61]:
sum(v)

[1] -9.723764

In [62]:
max(v)

[1] 0.1168301

In [63]:
mean(v)
min(v)
sd(v)

[1] -0.9723764

[1] -2.451356

[1] 1.026799

In [64]:
s <- sd(v)

In [65]:
print(s)

[1] 1.026799


# The Matrix

In [66]:
x1 <- c(4,5,6)
x2 <- c(55,55,77)

In [67]:
m <- cbind(x1,x2)

In [68]:
print(m) # m is a 3*2 matrix

     x1 x2
[1,]  4 55
[2,]  5 55
[3,]  6 77


In [69]:
m2 <- rbind(x1,x2)

In [70]:
print(m2)

   [,1] [,2] [,3]
x1    4    5    6
x2   55   55   77


In [72]:
a <- matrix(0, nrow=5, ncol=3)
print(a)

     [,1] [,2] [,3]
[1,]    0    0    0
[2,]    0    0    0
[3,]    0    0    0
[4,]    0    0    0
[5,]    0    0    0


In [73]:
dat <- rnorm(15)
b <- matrix(dat, ncol=3)

In [74]:
print(b)

           [,1]       [,2]       [,3]
[1,] -1.3195576  0.1635163 -0.8525955
[2,]  0.6720154  0.2574400  0.3335416
[3,] -0.1421279  1.3718647 -0.9342615
[4,] -1.3794724 -0.6634456 -1.6401311
[5,]  0.6799839  0.2406687  0.7825773


In [75]:
b <- matrix("foo", ncol=3,nrow=5)

In [76]:
print(b)

     [,1]  [,2]  [,3] 
[1,] "foo" "foo" "foo"
[2,] "foo" "foo" "foo"
[3,] "foo" "foo" "foo"
[4,] "foo" "foo" "foo"
[5,] "foo" "foo" "foo"


# Indexing in Matrices

In [77]:
dat <- sample(12)
m <- matrix(dat, ncol=3)

In [78]:
print(m)

     [,1] [,2] [,3]
[1,]    1   10    3
[2,]    4   12    7
[3,]   11    6    2
[4,]    5    9    8


In [79]:
m[1,2] #first row second column

[1] 10

In [80]:
m[1:2,3]

[1] 3 7

In [81]:
m[1,]

[1]  1 10  3

In [82]:
m[,3] <- 0

In [83]:
print(m)

     [,1] [,2] [,3]
[1,]    1   10    0
[2,]    4   12    0
[3,]   11    6    0
[4,]    5    9    0


In [84]:
m[1:2,2]<-99

In [85]:
print(m)

     [,1] [,2] [,3]
[1,]    1   99    0
[2,]    4   99    0
[3,]   11    6    0
[4,]    5    9    0


In [86]:
num_rows <- nrow(m)

In [87]:
print(num_rows)

[1] 4


In [88]:
ncol(m)

[1] 3

In [89]:
colSums(m)

[1]  21 213   0

In [90]:
rowSums(m)

[1] 100 103  17  14

In [91]:
haha <- sample(15)
print(haha)

 [1]  9 10  5 13 15  7 14 12  2  3 11  8  6  4  1


# The DataFrame

In [92]:
id <- seq(4)
score <- rnorm(4)
names <- c("john","paul","george","ringo")
vocals <- c(TRUE, TRUE, FALSE, FALSE)
dset <- data.frame(id, names, score, vocals)

In [93]:
print(dset)

  id  names      score vocals
1  1   john  1.1960964   TRUE
2  2   paul -0.4199052   TRUE
3  3 george  0.1057735  FALSE
4  4  ringo -1.2609178  FALSE


In [94]:
dset[1,2]

[1] john
Levels: george john paul ringo

In [95]:
dset$names

[1] john   paul   george ringo 
Levels: george john paul ringo

In [96]:
id <- seq(4)
score <- rnorm(4)
names <- c("john","paul","george","ringo")
vocals <- c(TRUE, TRUE, FALSE, FALSE)
dset <- data.frame(id, names, score, vocals, stringsAsFactors=FALSE)

In [97]:
print(dset)

  id  names      score vocals
1  1   john  0.6576127   TRUE
2  2   paul -1.6405542   TRUE
3  3 george  0.5596275  FALSE
4  4  ringo -1.1402574  FALSE


In [98]:
dset[1,2]

[1] "john"